# SOL detection rules

SOL detection rules let you write detection logic directly in Sekoia Query Language (SOL), turning your investigations into active detections without any conversion step. This article explains what SOL detection rules are, how they work, and when to use them.

## What are SOL detection rules

SOL detection rules are a detection rule type that executes a SOL query on a defined schedule and generates alerts when the query returns results. Unlike Sigma-based rules, they allow you to use your existing SOL investigation queries as-is, bridging the gap between investigation and prevention in a single workflow.

## Rule types

There are two types of SOL-based detection rules:

| Type | Purpose |
|---|---|
| **SOL rule** | Executes a SOL query on a schedule and raises a security alert when results are returned |
| **Event Drop rule** | Monitors assets or intakes for missing or dropped events and alerts you when expected data stops flowing |

> 📸 [SCREENSHOT SUGGESTION: Rule catalog view with SOL and Event Drop rule type badges/filters visible | ALT TEXT: Rule catalog showing SOL and Event Drop rule type filters.]

## How SOL detection rules work

When you create a SOL detection rule, the platform executes your query at the interval you define using a cron expression. Each execution is logged so you can audit the rule's history over time.

To reduce alert noise, you can configure the rule to group related events into a single alert instead of creating one alert per result row.

!!! note "Result cap"
    SOL detection rules automatically cap query results at 10,000 rows per execution. Queries that would return more rows are truncated at that limit.

Rules start executing immediately after creation. Results and execution history are accessible directly from the alert view.

## Alerts generated by SOL detection rules

Alerts generated by SOL and Event Drop rules include two dedicated tabs:

- **Results**: Displays the raw, paginated results returned by the query for that execution.
- **History**: Shows the full execution history of the rule, allowing you to track past runs and identify gaps or anomalies.

!!! note "Event Drop alerts"
    Alerts generated by Event Drop rules do not include threat intelligence context, Kill Chain phase, or TI context sections, as these are not applicable to availability monitoring.

## When to use SOL detection rules

- You have already written a SOL query during an investigation and want to operationalize it as a standing detection without rewriting it in Sigma.
- You want to detect patterns or conditions that are difficult to express in standard Sigma syntax.
- You need to monitor assets or intakes for data availability issues using an Event Drop rule.

## Related links

- [Create a SOL detection rule](/xdr/features/detect/create_sol_detection_rule.md) - Step-by-step instructions to configure and activate a SOL or Event Drop detection rule.
- [Write queries in SOL](/xdr/features/investigate/sol_how_to_guides.md) - Reference guide for SOL syntax, operators, and functions.
