name: Mark old PRs as stale

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions: {}

jobs:
  close-issues:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to label and comment on stale pull requests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ascending: true
          days-before-issue-close: -1
          days-before-issue-stale: -1
          days-before-pr-close: -1
          days-before-pr-stale: 30
          operations-per-run: 1000
          stale-issue-label: "stale"
          stale-pr-message: "This PR was marked as stale because it has been open for 30 days with no activity."
