name: Ask preview removal for a given PR

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          mkdir PR
          echo ${{ github.event.number }} > ./PR/PR_NUMBER

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: PR
          path: PR/
