name: Spelling

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**.md"
      - "docs/**/**.md"

env:
  CLICOLOR: 1

permissions: {}

jobs:
  spelling:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for tj-actions/changed-files to list changed files via pulls.listFiles API
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repo under $GITHUB_WORKSPACE
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          use_rest_api: true
          files: |
            docs/**/*.md
            !docs/assets/**/*

      - name: Spell Check Repo
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1.49.0
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
