name: Update assets connectors documentation
on:
  workflow_dispatch:
  repository_dispatch:
    types: [rebuild-assets-documentation]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout `documentation` repository under `main/`
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: main

    - name: Checkout `automation-module` repository under `asset_connectors/`
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: SEKOIA-IO/automation-module
        path: asset_connectors

    - name: Install uv
      uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
      with:
        enable-cache: true

    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      id: setup-python
      with:
        python-version: '3.14'

    - name: Refresh assets connectors documentation
      run: |
        rm -rf ../../_shared_content/operations_center/integrations/generated_assets_documentation/*.md
        uv run python update_mkdocs_asset_connectors.py $GITHUB_WORKSPACE/asset_connectors $GITHUB_WORKSPACE/main
      working-directory: ./main/scripts/update_mkdocs

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        commit-message: Refresh assets connectors documentation
        delete-branch: true
        title: Refresh assets connectors documentation
        base: main
        path: ./main
        branch: update-assets-documentation
        body: |
          Refresh assets connectors documentation
