name: Update assets connectors documentation
on:
  workflow_dispatch:
  repository_dispatch:
    types: [rebuild-assets-documentation]

permissions: {}

jobs:
  build:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout `documentation` repository under `main/`
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        path: main

    - name: Checkout `automation-module` repository under `asset_connectors/`
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: SEKOIA-IO/automation-module
        path: asset_connectors

    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        enable-cache: true

    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      id: setup-python
      with:
        python-version: '3.14'

    - name: Refresh assets connectors documentation
      run: |
        rm -rf ../../_shared_content/operations_center/integrations/generated_assets_documentation/*.md
        uv run python update_mkdocs_asset_connectors.py "$GITHUB_WORKSPACE/asset_connectors" "$GITHUB_WORKSPACE/main"
      working-directory: ./main/scripts/update_mkdocs

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        commit-message: Refresh assets connectors documentation
        delete-branch: true
        title: Refresh assets connectors documentation
        base: main
        path: ./main
        branch: update-assets-documentation
        body: |
          Refresh assets connectors documentation
